### PR TITLE
fix #20: Takes into account dependencies specifically added for the plugin

### LINKED ISSUE #20: Specific plugin dependencies are not added to classpath
When I add a specific dependency in plugin declaration, for example:

```xml
<plugin>
	<groupId>com.github.johnpoth</groupId>
	<artifactId>jshell-maven-plugin</artifactId>
	<version>1.3</version>
	<executions>
		<execution>
			<id>generate-PlantUML</id>
			<phase>generate-resources</phase>
			<goals>
				<goal>run</goal>
			</goals>
			<configuration>
				<scripts>${project.basedir}/src/site/script/GeneratePlantUmlFormOpenApi.jsh</scripts>
				<options>
					<option>-R "-DopenApiSourceFile=${project.basedir}/src/site/resources/openapi-spec.json"</option>
					<option>-R "-DopenApiTargetPlantUmlFile=${project.build.directory}/openapi-plantuml/openapi-spec.puml"</option>
				</options>
			</configuration>
		</execution>
	</executions>
	<dependencies>
		<dependency>
			<groupId>com.github.davidmoten</groupId>
			<artifactId>openapi-to-plantuml</artifactId>
			<version>0.1.21</version>
		</dependency>
	</dependencies>
</plugin>
```

... those dependency is not "injected" in classpath when jshell in run:

```
Error:
package com.github.davidmoten.oas3.puml does not exist
import com.github.davidmoten.oas3.puml.Converter;
       ^---------------------------------------^
Error:
cannot find symbol
  symbol:   variable GeneratePlantUmlFormOpenApi
        GeneratePlantUmlFormOpenApi.main();
 ^-------------------------^
```

### PR DESCRIPTION
**Pull request by jycr**
Add specific dependencies added to plugins, for example via:

```
<plugin>
	<groupId>com.github.johnpoth</groupId>
	<artifactId>jshell-maven-plugin</artifactId>
	<!-- ... -->
	<dependencies>
		<dependency>
			<groupId>com.acme</groupId>
			<artifactId>other-dependency</artifactId>
			<version>X.X.X</version>
		</dependency>
	</dependencies>
</plugin>
```

### CODE REVIEW

**Review by johnpoth — APPROVED** [review]

**Comment by johnpoth** [comment]
Looks good to me! Thanks for the contributions ! I'm about to cut a release with these changes, would you be able to test it out ? Thanks !

**Comment by jycr** [comment]
> would you be able to test it out ?

I plan to use this plugin now in 2 projects. So I can do some testing.

**Comment by johnpoth** [comment]
Cool thanks! It's in staging now:

https://oss.sonatype.org/service/local/repositories/comgithubjohnpoth-1010/content/com/github/johnpoth/jshell-maven-plugin/1.4/jshell-maven-plugin-1.4.jar

Thanks !

**Comment by johnpoth** [comment]
Released ! Thanks!

**Pull request merged**
